[theme]
primaryColor = "#2D6A4F"
backgroundColor = "#0B0E11"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#FFFFFF"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
